### PR TITLE
Add wayland support

### PR DESCRIPTION
**Pull request by pixelherodev**

### CODE REVIEW

**Comment by pixelherodev** [comment]
Suggestion: adding -wayland configuration options in Oryol

**Comment by floooh** [comment]
Thanks! I'll try to merge this on Monday, I'm currently away from my Linux laptop, and don't want to merge blindly (even though I had already tested it I want to check again before merging).

**Comment by floooh** [comment]
Tested and merged, thanks!

**Comment by pixelherodev** [comment]
No problem!

**Pull request merged**
